//! `moochy-proto`: the protocol core every other Moochy component trusts.
//!
//! - [`enc`]: `lp`, labels, base64url, ULID ids (CONTRACT §1–2)
//! - [`json`]: parser-differential-safe JSON (CONTRACT §1)
//! - [`pb`]: generated protobuf + gRPC stubs for `spec/proto/moochy/v1/link.proto` (CONTRACT §12)
//! - [`msg`]: signed JSON artifacts: route header, inner payload, receipt, projection, catalog
//! - [`crypto`]: keys, envelopes, HPKE wraps, signatures (CONTRACT §3)
//! - [`money`]: catalog entry, cost, reservation, deterministic input estimate (plan 05)
//! - [`username`]: shared handle validator (CONTRACT §11) and safe display of remote strings
#![forbid(unsafe_code)]
#![cfg_attr(
    test,
    allow(
        clippy::unwrap_used,
        clippy::expect_used,
        clippy::panic,
        clippy::indexing_slicing,
        clippy::arithmetic_side_effects
    )
)]

pub mod crypto;
pub mod enc;
pub mod json;
pub mod money;
pub mod msg;
pub mod username;

/// Generated by `cli/crates/proto/pbgen` from `spec/proto/moochy/v1/link.proto` (committed;
/// builds never run protoc). Every `bytes` field is `bytes::Bytes`.
#[allow(clippy::all, clippy::pedantic, clippy::unwrap_used, clippy::expect_used, clippy::panic, clippy::indexing_slicing, clippy::arithmetic_side_effects, missing_docs)]
pub mod pb {
    include!("pb/moochy.v1.rs");
}

pub use enc::{B, Blob, DeviceId, PledgeId, RepoId, Sig, TaskId, Ulid, UserId, b64, lp, unb64};

/// One error type, deliberately coarse: callers map it to a wire code, never to a message
/// that could leak secrets. `Decrypt`/`BadSignature`/`Hash`/`Sequence` → nack `bad_envelope`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Error {
    /// Bad encoding: base64, id, wrong JSON shape or field, wrong length.
    Malformed,
    /// JSON parser-differential rule violated (duplicate key, depth, number range, UTF-8, trailing data).
    Json,
    /// A hard size bound was exceeded (chunk, body, decompression bomb).
    TooLarge,
    /// AEAD or HPKE authentication failed.
    Decrypt,
    /// Ed25519 (ZIP-215) verification failed or malformed key/signature.
    BadSignature,
    /// A committed hash did not match (e.g. `body_sha256`).
    Hash,
    /// Chunk out of order, for the wrong attempt, or after the last chunk.
    Sequence,
    /// Checked integer arithmetic overflowed or a money input is out of range.
    Overflow,
    /// The OS random generator failed.
    Rng,
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        std::fmt::Debug::fmt(self, f)
    }
}
impl std::error::Error for Error {}
