// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NodeMsg {
    #[prost(oneof = "node_msg::Msg", tags = "1, 2, 3, 4, 5, 6, 7")]
    pub msg: ::core::option::Option<node_msg::Msg>,
}
/// Nested message and enum types in `NodeMsg`.
pub mod node_msg {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Msg {
        #[prost(message, tag = "1")]
        Auth(super::Auth),
        #[prost(message, tag = "2")]
        Offer(super::WorkerOffer),
        #[prost(message, tag = "3")]
        KnownTasks(super::KnownTasks),
        #[prost(message, tag = "4")]
        Dispute(super::ReceiptDispute),
        #[prost(message, tag = "5")]
        ReplayReceipt(super::ReplayReceipt),
        #[prost(message, tag = "6")]
        Ping(super::Ping),
        /// owner-signed claim / approval / membership (key log)
        #[prost(message, tag = "7")]
        LogEntry(super::SignedLogEntry),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RelayMsg {
    #[prost(
        oneof = "relay_msg::Msg",
        tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13"
    )]
    pub msg: ::core::option::Option<relay_msg::Msg>,
}
/// Nested message and enum types in `RelayMsg`.
pub mod relay_msg {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Msg {
        #[prost(message, tag = "1")]
        Hello(super::Hello),
        #[prost(message, tag = "2")]
        Welcome(super::Welcome),
        #[prost(message, tag = "3")]
        PoolSync(super::PoolSync),
        #[prost(message, tag = "4")]
        Assign(super::AssignNotice),
        #[prost(message, tag = "5")]
        LogCheckpoint(super::LogCheckpoint),
        #[prost(message, tag = "6")]
        Catalog(super::CatalogUpdate),
        #[prost(message, tag = "7")]
        Draining(super::Draining),
        #[prost(message, tag = "8")]
        ReplaySince(super::ReceiptReplaySince),
        #[prost(message, tag = "9")]
        ReceiptAck(super::ReceiptAck),
        #[prost(message, tag = "10")]
        Pong(super::Pong),
        #[prost(message, tag = "11")]
        Error(super::Error),
        #[prost(message, tag = "12")]
        LogEntryAck(super::LogEntryAck),
        /// pushed to repo owners' Nodes
        #[prost(message, tag = "13")]
        ApprovalRequests(super::ApprovalRequests),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Hello {
    /// 32 random bytes
    #[prost(bytes = "bytes", tag = "1")]
    pub nonce: ::prost::bytes::Bytes,
    #[prost(int64, tag = "2")]
    pub server_time_ms: i64,
    #[prost(string, tag = "3")]
    pub min_client_version: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub relay_release: ::prost::alloc::string::String,
    /// signed-note bytes of the latest key-log checkpoint (may be empty)
    #[prost(bytes = "bytes", tag = "5")]
    pub log_checkpoint: ::prost::bytes::Bytes,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Auth {
    #[prost(string, tag = "1")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(enumeration = "Role", repeated, tag = "2")]
    pub roles: ::prost::alloc::vec::Vec<i32>,
    /// see header comment
    #[prost(bytes = "bytes", tag = "3")]
    pub sig: ::prost::bytes::Bytes,
    #[prost(string, tag = "4")]
    pub client_version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Welcome {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(enumeration = "Role", repeated, tag = "2")]
    pub roles: ::prost::alloc::vec::Vec<i32>,
    #[prost(uint32, tag = "3")]
    pub max_concurrent_tasks: u32,
    #[prost(uint64, tag = "4")]
    pub catalog_version: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PoolSync {
    #[prost(string, tag = "1")]
    pub repo_id: ::prost::alloc::string::String,
    /// true: replace the pool; false: upsert workers + remove listed ones
    #[prost(bool, tag = "2")]
    pub full: bool,
    #[prost(message, repeated, tag = "3")]
    pub workers: ::prost::alloc::vec::Vec<PoolWorker>,
    #[prost(string, repeated, tag = "4")]
    pub removed_worker_devices: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// "owner/name" (lowercase), for repo-scoped local tokens
    #[prost(string, tag = "5")]
    pub repo_slug: ::prost::alloc::string::String,
    /// "github" | "gitlab"
    #[prost(string, tag = "6")]
    pub repo_provider: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PoolWorker {
    #[prost(string, tag = "1")]
    pub worker_device: ::prost::alloc::string::String,
    /// X25519 public key (32 bytes)
    #[prost(bytes = "bytes", tag = "2")]
    pub enc_pub: ::prost::bytes::Bytes,
    #[prost(uint64, tag = "3")]
    pub key_log_index: u64,
    #[prost(uint64, tag = "4")]
    pub approval_log_index: u64,
    #[prost(string, tag = "5")]
    pub donor_pseudonym: ::prost::alloc::string::String,
    /// "anthropic.messages" | "openai.chat"
    #[prost(string, repeated, tag = "6")]
    pub dialects: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// public model ids (slugs)
    #[prost(string, repeated, tag = "7")]
    pub models: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 0-100, coarse
    #[prost(uint32, tag = "8")]
    pub hint: u32,
    /// Ed25519 key of the worker device (verifies receipts, progress checkpoints)
    #[prost(bytes = "bytes", tag = "9")]
    pub sign_pub: ::prost::bytes::Bytes,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorkerOffer {
    #[prost(uint32, tag = "1")]
    pub slots_free: u32,
    #[prost(message, repeated, tag = "2")]
    pub models: ::prost::alloc::vec::Vec<ModelOffer>,
    #[prost(string, repeated, tag = "3")]
    pub pledges: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, tag = "4")]
    pub window_open: bool,
    #[prost(int64, tag = "5")]
    pub local_cap_left_uusd: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ModelOffer {
    #[prost(string, tag = "1")]
    pub dialect: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub model: ::prost::alloc::string::String,
    /// 0-100
    #[prost(uint32, tag = "3")]
    pub rl_headroom: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KnownTasks {
    #[prost(message, repeated, tag = "1")]
    pub tasks: ::prost::alloc::vec::Vec<KnownTask>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct KnownTask {
    #[prost(string, tag = "1")]
    pub task: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub attempt: u32,
    /// "running" | "outbox"
    #[prost(string, tag = "3")]
    pub state: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AssignNotice {
    #[prost(string, tag = "1")]
    pub task: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub attempt: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReceiptDispute {
    #[prost(string, tag = "1")]
    pub task: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub attempt: u32,
    #[prost(string, tag = "3")]
    pub code: ::prost::alloc::string::String,
    /// Ed25519 over lp("moochy/v1/dispute", task, u64(attempt), code)
    #[prost(bytes = "bytes", tag = "4")]
    pub gateway_sig: ::prost::bytes::Bytes,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplayReceipt {
    #[prost(message, optional, tag = "1")]
    pub receipt: ::core::option::Option<SignedReceipt>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReceiptReplaySince {
    #[prost(int64, tag = "1")]
    pub since_ms: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReceiptAck {
    #[prost(string, tag = "1")]
    pub task: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub attempt: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogCheckpoint {
    /// signed-note bytes
    #[prost(bytes = "bytes", tag = "1")]
    pub note: ::prost::bytes::Bytes,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CatalogUpdate {
    #[prost(uint64, tag = "1")]
    pub version: u64,
    /// exact signed bytes
    #[prost(bytes = "bytes", tag = "2")]
    pub catalog_json: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "3")]
    pub sig: ::prost::bytes::Bytes,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Draining {
    #[prost(uint32, tag = "1")]
    pub reconnect_after_ms: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Ping {
    #[prost(int64, tag = "1")]
    pub t_ms: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Pong {
    #[prost(int64, tag = "1")]
    pub t_ms: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Error {
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub task: ::prost::alloc::string::String,
}
/// Owner-signed key-log entries (formats defined by the key-log spec, kind = KEY\_\* / REPO_CLAIMED /
/// DONOR_APPROVED / DONOR_REVOKED / MEMBER_ADDED / MEMBER_REMOVED). `body` is the exact signed bytes.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SignedLogEntry {
    /// client-chosen id, echoed in LogEntryAck
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub kind: ::prost::alloc::string::String,
    #[prost(bytes = "bytes", tag = "3")]
    pub body: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", repeated, tag = "4")]
    pub sigs: ::prost::alloc::vec::Vec<::prost::bytes::Bytes>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogEntryAck {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    /// position in the key log once appended
    #[prost(uint64, tag = "2")]
    pub index: u64,
    /// empty on success
    #[prost(string, tag = "3")]
    pub error: ::prost::alloc::string::String,
}
/// Requests waiting for a repo owner's signature (donor approvals, member additions, repo claims).
/// The owner's Node MUST parse `body_to_sign`, show its meaning to the owner, and sign only on an
/// explicit `moochy approve` / `moochy members add` / `moochy claim`; it never signs what the relay
/// proposes automatically.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ApprovalRequests {
    #[prost(message, repeated, tag = "1")]
    pub requests: ::prost::alloc::vec::Vec<ApprovalRequest>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ApprovalRequest {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub kind: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub repo_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub repo_slug: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub subject_username: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub subject_pseudonym: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub pledge_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "8")]
    pub created_at_ms: i64,
    #[prost(bytes = "bytes", tag = "9")]
    pub body_to_sign: ::prost::bytes::Bytes,
    /// human-readable, for display only (never signed as-is)
    #[prost(string, tag = "10")]
    pub summary: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogTileRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogTileResponse {
    #[prost(bytes = "bytes", tag = "1")]
    pub data: ::prost::bytes::Bytes,
}
/// AEAD ciphertext chunk. For request bodies attempt = 0. Plaintext \<= 65,497 bytes.
/// AAD binds task id, attempt, seq and last (CONTRACT §3); the stream itself identifies the task.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Chunk {
    #[prost(uint32, tag = "1")]
    pub attempt: u32,
    #[prost(uint32, tag = "2")]
    pub seq: u32,
    #[prost(bool, tag = "3")]
    pub last: bool,
    #[prost(bytes = "bytes", tag = "4")]
    pub ct: ::prost::bytes::Bytes,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Wrap {
    #[prost(string, tag = "1")]
    pub worker_device: ::prost::alloc::string::String,
    /// 80 bytes: HPKE enc (32) || ct (48)
    #[prost(bytes = "bytes", tag = "2")]
    pub wrap: ::prost::bytes::Bytes,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Checkpoint {
    #[prost(uint32, tag = "1")]
    pub attempt: u32,
    #[prost(uint32, tag = "2")]
    pub seq: u32,
    #[prost(bytes = "bytes", tag = "3")]
    pub running_hash: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "4")]
    pub sig: ::prost::bytes::Bytes,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SignedReceipt {
    #[prost(string, tag = "1")]
    pub task: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub attempt: u32,
    /// exact signed JSON bytes
    #[prost(bytes = "bytes", tag = "3")]
    pub receipt: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "4")]
    pub donor_sig: ::prost::bytes::Bytes,
    /// exact signed JSON bytes
    #[prost(bytes = "bytes", tag = "5")]
    pub projection: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "6")]
    pub projection_sig: ::prost::bytes::Bytes,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Cancel {
    #[prost(string, tag = "1")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Failed {
    /// CONTRACT / plan 03 §10.2-10.3 codes
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub retryable: bool,
    #[prost(uint32, tag = "3")]
    pub retry_after_ms: u32,
    /// detail sealed to the Gateway (Relay sees only `code`)
    #[prost(bytes = "bytes", tag = "4")]
    pub sealed_detail: ::prost::bytes::Bytes,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubmitUp {
    #[prost(oneof = "submit_up::Msg", tags = "1, 2, 3, 4")]
    pub msg: ::core::option::Option<submit_up::Msg>,
}
/// Nested message and enum types in `SubmitUp`.
pub mod submit_up {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Msg {
        #[prost(message, tag = "1")]
        Open(super::SubmitOpen),
        #[prost(message, tag = "2")]
        Body(super::Chunk),
        /// answer to NeedWraps
        #[prost(message, tag = "3")]
        Wraps(super::Wraps),
        #[prost(message, tag = "4")]
        Cancel(super::Cancel),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubmitOpen {
    #[prost(string, tag = "1")]
    pub task: ::prost::alloc::string::String,
    /// exact route-header JSON bytes (bound as HPKE AAD)
    #[prost(bytes = "bytes", tag = "2")]
    pub route: ::prost::bytes::Bytes,
    /// \<= 8
    #[prost(message, repeated, tag = "3")]
    pub wraps: ::prost::alloc::vec::Vec<Wrap>,
    #[prost(uint64, tag = "4")]
    pub body_len: u64,
    #[prost(uint32, tag = "5")]
    pub body_chunks: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Wraps {
    #[prost(message, repeated, tag = "1")]
    pub wraps: ::prost::alloc::vec::Vec<Wrap>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubmitDown {
    #[prost(oneof = "submit_down::Msg", tags = "1, 2, 3, 4, 5, 6, 7")]
    pub msg: ::core::option::Option<submit_down::Msg>,
}
/// Nested message and enum types in `SubmitDown`.
pub mod submit_down {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Msg {
        #[prost(message, tag = "1")]
        NeedWraps(super::NeedWraps),
        #[prost(message, tag = "2")]
        Accepted(super::Accepted),
        #[prost(message, tag = "3")]
        Started(super::Started),
        #[prost(message, tag = "4")]
        Chunk(super::Chunk),
        #[prost(message, tag = "5")]
        Checkpoint(super::Checkpoint),
        #[prost(message, tag = "6")]
        End(super::SignedReceipt),
        #[prost(message, tag = "7")]
        Failed(super::Failed),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NeedWraps {
    #[prost(string, repeated, tag = "1")]
    pub workers: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Accepted {
    #[prost(uint32, tag = "1")]
    pub attempt: u32,
    #[prost(string, tag = "2")]
    pub worker_device: ::prost::alloc::string::String,
    /// the Worker's per-attempt response salt
    #[prost(bytes = "bytes", tag = "3")]
    pub r: ::prost::bytes::Bytes,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Started {
    #[prost(uint32, tag = "1")]
    pub attempt: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ServeUp {
    #[prost(oneof = "serve_up::Msg", tags = "1, 2, 3, 4, 5, 6, 7")]
    pub msg: ::core::option::Option<serve_up::Msg>,
}
/// Nested message and enum types in `ServeUp`.
pub mod serve_up {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Msg {
        #[prost(message, tag = "1")]
        Open(super::ServeOpen),
        #[prost(message, tag = "2")]
        Ack(super::Ack),
        #[prost(message, tag = "3")]
        Nack(super::Nack),
        #[prost(message, tag = "4")]
        Started(super::Started),
        #[prost(message, tag = "5")]
        Chunk(super::Chunk),
        #[prost(message, tag = "6")]
        Checkpoint(super::Checkpoint),
        #[prost(message, tag = "7")]
        End(super::SignedReceipt),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ServeOpen {
    #[prost(string, tag = "1")]
    pub task: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub attempt: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Ack {
    #[prost(bytes = "bytes", tag = "1")]
    pub r: ::prost::bytes::Bytes,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Nack {
    #[prost(bytes = "bytes", tag = "1")]
    pub r: ::prost::bytes::Bytes,
    #[prost(string, tag = "2")]
    pub code: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub retryable: bool,
    #[prost(uint32, tag = "4")]
    pub retry_after_ms: u32,
    #[prost(bytes = "bytes", tag = "5")]
    pub sealed_detail: ::prost::bytes::Bytes,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ServeDown {
    #[prost(oneof = "serve_down::Msg", tags = "1, 2, 3, 4")]
    pub msg: ::core::option::Option<serve_down::Msg>,
}
/// Nested message and enum types in `ServeDown`.
pub mod serve_down {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Msg {
        #[prost(message, tag = "1")]
        Assign(super::Assign),
        #[prost(message, tag = "2")]
        Body(super::Chunk),
        #[prost(message, tag = "3")]
        Cancel(super::Cancel),
        #[prost(message, tag = "4")]
        ReceiptAck(super::ReceiptAck),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Assign {
    #[prost(string, tag = "1")]
    pub task: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub attempt: u32,
    /// exact route-header JSON bytes
    #[prost(bytes = "bytes", tag = "3")]
    pub route: ::prost::bytes::Bytes,
    /// this worker's wrap
    #[prost(bytes = "bytes", tag = "4")]
    pub wrap: ::prost::bytes::Bytes,
    #[prost(string, tag = "5")]
    pub pledge_id: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub repo_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "7")]
    pub deadline_ack_ms: u32,
    #[prost(uint64, tag = "8")]
    pub body_len: u64,
    #[prost(uint32, tag = "9")]
    pub body_chunks: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeviceStartRequest {
    /// Ed25519 public key
    #[prost(bytes = "bytes", tag = "1")]
    pub sign_pub: ::prost::bytes::Bytes,
    /// X25519 public key
    #[prost(bytes = "bytes", tag = "2")]
    pub enc_pub: ::prost::bytes::Bytes,
    #[prost(enumeration = "Role", repeated, tag = "3")]
    pub roles: ::prost::alloc::vec::Vec<i32>,
    #[prost(string, tag = "4")]
    pub name: ::prost::alloc::string::String,
    /// envelope suite id
    #[prost(string, tag = "5")]
    pub suite: ::prost::alloc::string::String,
    /// Ed25519(sign key, lp("moochy/v1/device-start", sign_pub, enc_pub, roles_csv, name, suite))
    #[prost(bytes = "bytes", tag = "6")]
    pub sig: ::prost::bytes::Bytes,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeviceStartResponse {
    /// "XXXX-XXXX", shown to the user
    #[prost(string, tag = "1")]
    pub user_code: ::prost::alloc::string::String,
    /// secret, used only for polling
    #[prost(string, tag = "2")]
    pub device_code: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub poll_interval_ms: u32,
    #[prost(int64, tag = "4")]
    pub expires_at_ms: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DevicePollRequest {
    #[prost(string, tag = "1")]
    pub device_code: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DevicePollResponse {
    #[prost(enumeration = "DeviceState", tag = "1")]
    pub state: i32,
    #[prost(string, tag = "2")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub user_pseudonym: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub username: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Role {
    Unspecified = 0,
    Gateway = 1,
    Worker = 2,
}
impl Role {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ROLE_UNSPECIFIED",
            Self::Gateway => "ROLE_GATEWAY",
            Self::Worker => "ROLE_WORKER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ROLE_UNSPECIFIED" => Some(Self::Unspecified),
            "ROLE_GATEWAY" => Some(Self::Gateway),
            "ROLE_WORKER" => Some(Self::Worker),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DeviceState {
    Unspecified = 0,
    Pending = 1,
    Approved = 2,
    Denied = 3,
    Expired = 4,
}
impl DeviceState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "DEVICE_STATE_UNSPECIFIED",
            Self::Pending => "DEVICE_STATE_PENDING",
            Self::Approved => "DEVICE_STATE_APPROVED",
            Self::Denied => "DEVICE_STATE_DENIED",
            Self::Expired => "DEVICE_STATE_EXPIRED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DEVICE_STATE_UNSPECIFIED" => Some(Self::Unspecified),
            "DEVICE_STATE_PENDING" => Some(Self::Pending),
            "DEVICE_STATE_APPROVED" => Some(Self::Approved),
            "DEVICE_STATE_DENIED" => Some(Self::Denied),
            "DEVICE_STATE_EXPIRED" => Some(Self::Expired),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod node_link_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct NodeLinkClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl<T> NodeLinkClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> NodeLinkClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            NodeLinkClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Long-lived control stream. Exactly one per connection. First server message: Hello.
        pub async fn session(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::NodeMsg>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::RelayMsg>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/moochy.v1.NodeLink/Session",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("moochy.v1.NodeLink", "Session"));
            self.inner.streaming(req, path, codec).await
        }
        /// Gateway role: one stream per task. First client message: SubmitOpen.
        pub async fn submit(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::SubmitUp>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::SubmitDown>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/moochy.v1.NodeLink/Submit",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut().insert(GrpcMethod::new("moochy.v1.NodeLink", "Submit"));
            self.inner.streaming(req, path, codec).await
        }
        /// Worker role: one stream per assigned attempt, opened after an AssignNotice on Session.
        /// First client message: ServeOpen. First server message: Assign.
        pub async fn serve(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::ServeUp>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ServeDown>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/moochy.v1.NodeLink/Serve");
            let mut req = request.into_streaming_request();
            req.extensions_mut().insert(GrpcMethod::new("moochy.v1.NodeLink", "Serve"));
            self.inner.streaming(req, path, codec).await
        }
        /// Device login (unauthenticated, strictly rate-limited per IP).
        pub async fn device_start(
            &mut self,
            request: impl tonic::IntoRequest<super::DeviceStartRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeviceStartResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/moochy.v1.NodeLink/DeviceStart",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("moochy.v1.NodeLink", "DeviceStart"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn device_poll(
            &mut self,
            request: impl tonic::IntoRequest<super::DevicePollRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DevicePollResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/moochy.v1.NodeLink/DevicePoll",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("moochy.v1.NodeLink", "DevicePoll"));
            self.inner.unary(req, path, codec).await
        }
        /// Public key-log tiles and checkpoint (C2SP tlog-tiles paths, e.g. "tile/0/000", "checkpoint").
        /// Unauthenticated, strictly rate-limited per IP, response capped at 64 KiB. Lets Nodes mirror and
        /// verify the key log over the link they already have.
        pub async fn get_log_tile(
            &mut self,
            request: impl tonic::IntoRequest<super::LogTileRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LogTileResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/moochy.v1.NodeLink/GetLogTile",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("moochy.v1.NodeLink", "GetLogTile"));
            self.inner.unary(req, path, codec).await
        }
    }
}
