// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StatusRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatusResponse {
    #[prost(string, tag = "1")]
    pub version: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub roles: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "4")]
    pub relay: ::prost::alloc::string::String,
    /// "down" | "up" | "refused: <code>" | "offline"
    #[prost(string, tag = "5")]
    pub link_state: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub gateway_url: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub mcp_url: ::prost::alloc::string::String,
    #[prost(bool, tag = "8")]
    pub paused: bool,
    #[prost(uint32, tag = "9")]
    pub slots_max: u32,
    #[prost(uint32, tag = "10")]
    pub slots_busy: u32,
    /// in flight
    #[prost(uint32, tag = "11")]
    pub gateway_tasks: u32,
    #[prost(message, repeated, tag = "12")]
    pub pools: ::prost::alloc::vec::Vec<PoolSummary>,
    #[prost(uint32, tag = "13")]
    pub pid: u32,
    /// relay server_time − node clock at the last Hello (0 = unknown)
    #[prost(int64, tag = "14")]
    pub clock_skew_ms: i64,
    #[prost(uint32, tag = "15")]
    pub provider_keys: u32,
    #[prost(uint32, tag = "16")]
    pub warm_adapters: u32,
    #[prost(uint64, tag = "17")]
    pub catalog_version: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PoolSummary {
    #[prost(string, tag = "1")]
    pub repo_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub slug: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub workers: u32,
    #[prost(string, repeated, tag = "4")]
    pub models: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PauseRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PauseResponse {
    #[prost(bool, tag = "1")]
    pub paused: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EnvRequest {
    /// owner/name
    #[prost(string, tag = "1")]
    pub repo: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub rotate: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EnvResponse {
    #[prost(string, tag = "1")]
    pub anthropic_base_url: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub openai_base_url: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub mcp_url: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ApproveRequest {
    /// owner/name
    #[prost(string, tag = "1")]
    pub repo: ::prost::alloc::string::String,
    /// donor username (CONTRACT §11 handle) or pseudonym
    #[prost(string, tag = "2")]
    pub donor: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub dry_run: bool,
    /// DONOR_REVOKED instead of DONOR_APPROVED
    #[prost(bool, tag = "4")]
    pub revoke: bool,
    /// CONTRACT §19.4: "github/acme", "gitlab/group\[/sub…\]"; set = the org's approval (repo empty)
    #[prost(string, tag = "5")]
    pub org: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClaimRequest {
    #[prost(string, tag = "1")]
    pub repo: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub dry_run: bool,
    /// CONTRACT §19.2: set = ORG_CLAIMED of this org (repo empty)
    #[prost(string, tag = "3")]
    pub org: ::prost::alloc::string::String,
}
/// CONTRACT §19.3: which of the owner's projects an organisation's donations fund.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OrgRepoRequest {
    /// "github/acme", "gitlab/group\[/sub…\]"
    #[prost(string, tag = "1")]
    pub org: ::prost::alloc::string::String,
    /// a project in the link's canonical form
    #[prost(string, tag = "2")]
    pub repo: ::prost::alloc::string::String,
    /// ORG_REPO_REMOVED instead of ORG_REPO_ADDED
    #[prost(bool, tag = "3")]
    pub remove: bool,
    #[prost(bool, tag = "4")]
    pub dry_run: bool,
}
/// What the owner signs (or would sign), decoded from the exact body bytes.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SignResponse {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub kind: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub repo_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub repo_slug: ::prost::alloc::string::String,
    /// pseudonym / device id inside the signed body
    #[prost(string, tag = "5")]
    pub subject: ::prost::alloc::string::String,
    /// relay-provided, display only
    #[prost(string, tag = "6")]
    pub subject_username: ::prost::alloc::string::String,
    /// the signer named in the body (an owner key id `ok_…`)
    #[prost(string, tag = "7")]
    pub signer: ::prost::alloc::string::String,
    #[prost(int64, tag = "8")]
    pub issued_at_ms: i64,
    #[prost(bool, tag = "9")]
    pub signed: bool,
    /// once appended
    #[prost(uint64, tag = "10")]
    pub log_index: u64,
    /// the relay-proposed body (dry run), for the CLI to rebuild with the owner key
    #[prost(bytes = "vec", tag = "11")]
    pub body_to_sign: ::prost::alloc::vec::Vec<u8>,
    /// CONTRACT §19, from ApprovalRequest: display labels only (the CLI binds the decoded body and the
    /// server's Lookup). ORG_CLAIMED: repo_id empty; ORG_REPO\_*: repo_id = the project; DONOR\_* of an
    /// org: repo_id = org_id = the o\_ id in the body.
    #[prost(string, tag = "12")]
    pub org_id: ::prost::alloc::string::String,
    #[prost(string, tag = "13")]
    pub org_path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubmitEntryRequest {
    /// the pending request answered; empty for OWNER_KEY_ADDED
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    /// REPO_CLAIMED, DONOR_APPROVED/REVOKED, MEMBER_ADDED/REMOVED, OWNER_KEY_ADDED, ORG_CLAIMED, ORG_REPO_ADDED/REMOVED
    #[prost(string, tag = "2")]
    pub kind: ::prost::alloc::string::String,
    /// exact signed body (KEYLOG §2)
    #[prost(bytes = "vec", tag = "3")]
    pub body: ::prost::alloc::vec::Vec<u8>,
    /// 64-byte Ed25519 signatures (owner key; rotation: new, previous)
    #[prost(bytes = "vec", repeated, tag = "4")]
    pub sigs: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PendingRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PendingResponse {
    #[prost(message, repeated, tag = "1")]
    pub requests: ::prost::alloc::vec::Vec<SignResponse>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MembersRequest {
    #[prost(string, tag = "1")]
    pub repo: ::prost::alloc::string::String,
    #[prost(enumeration = "members_request::Op", tag = "2")]
    pub op: i32,
    /// username, pseudonym, or device id (with `device`)
    #[prost(string, tag = "3")]
    pub user: ::prost::alloc::string::String,
    /// 0 = repo default (relay-side setting, not signed)
    #[prost(int64, tag = "4")]
    pub cap_uusd_month: i64,
    /// the subject is a device (CI / headless node)
    #[prost(bool, tag = "5")]
    pub device: bool,
    #[prost(bool, tag = "6")]
    pub dry_run: bool,
}
/// Nested message and enum types in `MembersRequest`.
pub mod members_request {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Op {
        Unspecified = 0,
        Add = 1,
        Remove = 2,
    }
    impl Op {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unspecified => "OP_UNSPECIFIED",
                Self::Add => "OP_ADD",
                Self::Remove => "OP_REMOVE",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "OP_UNSPECIFIED" => Some(Self::Unspecified),
                "OP_ADD" => Some(Self::Add),
                "OP_REMOVE" => Some(Self::Remove),
                _ => None,
            }
        }
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JournalRequest {
    #[prost(bool, tag = "1")]
    pub follow: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JournalEntry {
    #[prost(int64, tag = "1")]
    pub t_ms: i64,
    /// "gateway" | "worker"
    #[prost(string, tag = "2")]
    pub role: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub task: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub repo: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub model: ::prost::alloc::string::String,
    /// ok | failed:<code> | cancelled | …
    #[prost(string, tag = "6")]
    pub status: ::prost::alloc::string::String,
    #[prost(int64, tag = "7")]
    pub cost_uusd: i64,
    /// duration
    #[prost(uint32, tag = "8")]
    pub ms: u32,
    /// only with `journal_full_text` (opt-in), bounded
    #[prost(bytes = "vec", tag = "9")]
    pub request: ::prost::alloc::vec::Vec<u8>,
    /// only with `journal_full_text` (opt-in), bounded
    #[prost(bytes = "vec", tag = "10")]
    pub response: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct McpOpen {
    /// owner/name ("" = detect from cwd)
    #[prost(string, tag = "1")]
    pub repo: ::prost::alloc::string::String,
    /// shim working directory: fallback MCP `files` root
    #[prost(string, tag = "2")]
    pub cwd: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct McpUp {
    #[prost(oneof = "mcp_up::Msg", tags = "1, 2")]
    pub msg: ::core::option::Option<mcp_up::Msg>,
}
/// Nested message and enum types in `McpUp`.
pub mod mcp_up {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Msg {
        #[prost(message, tag = "1")]
        Open(super::McpOpen),
        #[prost(bytes, tag = "2")]
        Data(::prost::alloc::vec::Vec<u8>),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct McpDown {
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ShutdownRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ShutdownResponse {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogoutRequest {
    /// \[a-z0-9.\_-\]{1,32}
    #[prost(string, tag = "1")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogoutResponse {
    /// the relay acknowledged the KEY_REVOKED request
    #[prost(bool, tag = "1")]
    pub revoked: bool,
    #[prost(string, tag = "2")]
    pub detail: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReportRequest {
    #[prost(string, tag = "1")]
    pub task: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReportResponse {
    /// JSON evidence bundle
    #[prost(bytes = "vec", tag = "1")]
    pub bundle: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DonationsRequest {
    /// list | donate | action
    #[prost(string, tag = "1")]
    pub op: ::prost::alloc::string::String,
    /// ListDonationsRequest | DonateRequest | DonationActionRequest
    #[prost(bytes = "vec", tag = "2")]
    pub request: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DonationsResponse {
    /// ListDonationsResponse | Donation
    #[prost(bytes = "vec", tag = "1")]
    pub response: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerifyRequest {
    #[prost(string, tag = "1")]
    pub receipt_ref: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerifyResponse {
    /// {"verified","receipt_ref","donor","revoked","repo_id","model","cost_uusd","day","trust"}
    #[prost(string, tag = "1")]
    pub result_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LinkCallRequest {
    #[prost(string, tag = "1")]
    pub op: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub request: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LinkCallResponse {
    #[prost(bytes = "vec", tag = "1")]
    pub response: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TrustOwnerKeyRequest {
    /// ok\_…
    #[prost(string, tag = "1")]
    pub owner_key_id: ::prost::alloc::string::String,
    /// only describe it
    #[prost(bool, tag = "2")]
    pub dry_run: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TrustOwnerKeyResponse {
    #[prost(string, tag = "1")]
    pub owner_key_id: ::prost::alloc::string::String,
    /// its OWNER_KEY_ADDED entry
    #[prost(uint64, tag = "2")]
    pub log_index: u64,
    #[prost(bool, tag = "3")]
    pub revoked: bool,
    /// acknowledged (false on a dry run)
    #[prost(bool, tag = "4")]
    pub trusted: bool,
}
/// Generated client implementations.
pub mod local_control_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct LocalControlClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl<T> LocalControlClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> LocalControlClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            LocalControlClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Node state at a glance. Must answer in well under 20 ms (CONTRACT §13).
        pub async fn status(
            &mut self,
            request: impl tonic::IntoRequest<super::StatusRequest>,
        ) -> std::result::Result<tonic::Response<super::StatusResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/moochy.v1.LocalControl/Status",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("moochy.v1.LocalControl", "Status"));
            self.inner.unary(req, path, codec).await
        }
        /// Local kill switch for the Worker role: instant, works offline, not persisted across restarts.
        pub async fn pause(
            &mut self,
            request: impl tonic::IntoRequest<super::PauseRequest>,
        ) -> std::result::Result<tonic::Response<super::PauseResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/moochy.v1.LocalControl/Pause",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("moochy.v1.LocalControl", "Pause"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn resume(
            &mut self,
            request: impl tonic::IntoRequest<super::PauseRequest>,
        ) -> std::result::Result<tonic::Response<super::PauseResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/moochy.v1.LocalControl/Resume",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("moochy.v1.LocalControl", "Resume"));
            self.inner.unary(req, path, codec).await
        }
        /// Base URLs + repo-scoped local token for tools (`moochy env`). `rotate` invalidates every token.
        pub async fn env(
            &mut self,
            request: impl tonic::IntoRequest<super::EnvRequest>,
        ) -> std::result::Result<tonic::Response<super::EnvResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/moochy.v1.LocalControl/Env",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("moochy.v1.LocalControl", "Env"));
            self.inner.unary(req, path, codec).await
        }
        /// Repo owner: sign a pending donor approval / membership change / repo claim with this device
        /// (plan 06 §5). The Node only signs a request the Relay pushed (ApprovalRequests), after
        /// checking its exact body; `dry_run` returns what would be signed without signing.
        pub async fn approve(
            &mut self,
            request: impl tonic::IntoRequest<super::ApproveRequest>,
        ) -> std::result::Result<tonic::Response<super::SignResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/moochy.v1.LocalControl/Approve",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("moochy.v1.LocalControl", "Approve"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn members(
            &mut self,
            request: impl tonic::IntoRequest<super::MembersRequest>,
        ) -> std::result::Result<tonic::Response<super::SignResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/moochy.v1.LocalControl/Members",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("moochy.v1.LocalControl", "Members"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn claim(
            &mut self,
            request: impl tonic::IntoRequest<super::ClaimRequest>,
        ) -> std::result::Result<tonic::Response<super::SignResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/moochy.v1.LocalControl/Claim",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("moochy.v1.LocalControl", "Claim"));
            self.inner.unary(req, path, codec).await
        }
        /// CONTRACT §19.3: ORG_REPO_ADDED / ORG_REPO_REMOVED previews (dry run only, like Claim).
        pub async fn org_repo(
            &mut self,
            request: impl tonic::IntoRequest<super::OrgRepoRequest>,
        ) -> std::result::Result<tonic::Response<super::SignResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/moochy.v1.LocalControl/OrgRepo",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("moochy.v1.LocalControl", "OrgRepo"));
            self.inner.unary(req, path, codec).await
        }
        /// Requests waiting for this owner's signature.
        pub async fn pending(
            &mut self,
            request: impl tonic::IntoRequest<super::PendingRequest>,
        ) -> std::result::Result<
            tonic::Response<super::PendingResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/moochy.v1.LocalControl/Pending",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("moochy.v1.LocalControl", "Pending"));
            self.inner.unary(req, path, codec).await
        }
        /// Owner key (CONTRACT §15.4, KEYLOG §4): the foreground CLI signed this key-log entry with the
        /// owner key after the user confirmed it; the Node never holds the owner key, it only relays the
        /// signed entry over its session and returns the relay's verdict. Approve/Members/Claim are then
        /// called with dry_run = true (preview only).
        pub async fn submit_entry(
            &mut self,
            request: impl tonic::IntoRequest<super::SubmitEntryRequest>,
        ) -> std::result::Result<tonic::Response<super::SignResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/moochy.v1.LocalControl/SubmitEntry",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("moochy.v1.LocalControl", "SubmitEntry"));
            self.inner.unary(req, path, codec).await
        }
        /// Donations (`moochy donate`, `moochy donations`): relayed as-is to NodeLink ListDonations /
        /// Donate / DonationAction on the node's authenticated session (the relay knows the user from
        /// the session, never from a field). `request`/`response` are the link.proto messages' bytes.
        pub async fn donations(
            &mut self,
            request: impl tonic::IntoRequest<super::DonationsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DonationsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/moochy.v1.LocalControl/Donations",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("moochy.v1.LocalControl", "Donations"));
            self.inner.unary(req, path, codec).await
        }
        /// `moochy verify <receipt_ref>` (E63): fetch the public projection over the link and check the
        /// donor's signature against the device key in this node's verified key-log mirror.
        pub async fn verify(
            &mut self,
            request: impl tonic::IntoRequest<super::VerifyRequest>,
        ) -> std::result::Result<tonic::Response<super::VerifyResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/moochy.v1.LocalControl/Verify",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("moochy.v1.LocalControl", "Verify"));
            self.inner.unary(req, path, codec).await
        }
        /// `moochy owner trust <ok_id>` (CONTRACT §16.6): mark an owner key of this account that was
        /// created elsewhere (a passkey registered on the web) as known, so the monitor stops alerting.
        pub async fn trust_owner_key(
            &mut self,
            request: impl tonic::IntoRequest<super::TrustOwnerKeyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TrustOwnerKeyResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/moochy.v1.LocalControl/TrustOwnerKey",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("moochy.v1.LocalControl", "TrustOwnerKey"));
            self.inner.unary(req, path, codec).await
        }
        /// Local audit journal (metadata only). `follow` keeps the stream open for new entries.
        pub async fn journal(
            &mut self,
            request: impl tonic::IntoRequest<super::JournalRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::JournalEntry>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/moochy.v1.LocalControl/Journal",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("moochy.v1.LocalControl", "Journal"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// stdio MCP shim: first message McpOpen, then raw newline-delimited JSON-RPC bytes both ways.
        pub async fn mcp_pipe(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::McpUp>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::McpDown>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/moochy.v1.LocalControl/McpPipe",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("moochy.v1.LocalControl", "McpPipe"));
            self.inner.streaming(req, path, codec).await
        }
        /// Graceful stop (`moochy down`).
        pub async fn shutdown(
            &mut self,
            request: impl tonic::IntoRequest<super::ShutdownRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ShutdownResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/moochy.v1.LocalControl/Shutdown",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("moochy.v1.LocalControl", "Shutdown"));
            self.inner.unary(req, path, codec).await
        }
        /// `moochy logout`: ask the relay to revoke this device (KEY_REVOKED), then stop.
        pub async fn logout(
            &mut self,
            request: impl tonic::IntoRequest<super::LogoutRequest>,
        ) -> std::result::Result<tonic::Response<super::LogoutResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/moochy.v1.LocalControl/Logout",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("moochy.v1.LocalControl", "Logout"));
            self.inner.unary(req, path, codec).await
        }
        /// `moochy report <task>`: evidence bundle for a task this Gateway consumed (06 §9): receipt,
        /// checkpoints, response bytes and only S_resp (never the request).
        pub async fn report(
            &mut self,
            request: impl tonic::IntoRequest<super::ReportRequest>,
        ) -> std::result::Result<tonic::Response<super::ReportResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/moochy.v1.LocalControl/Report",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("moochy.v1.LocalControl", "Report"));
            self.inner.unary(req, path, codec).await
        }
        /// Owner and member calls relayed as-is on the node's session (like Donations): `op` names the
        /// NodeLink RPC; `request`/`response` are its link.proto messages' bytes. Ops: set_device_cap,
        /// create_box_token, list_boxes, revoke_box.
        pub async fn link_call(
            &mut self,
            request: impl tonic::IntoRequest<super::LinkCallRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LinkCallResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/moochy.v1.LocalControl/LinkCall",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("moochy.v1.LocalControl", "LinkCall"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod local_control_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with LocalControlServer.
    #[async_trait]
    pub trait LocalControl: std::marker::Send + std::marker::Sync + 'static {
        /// Node state at a glance. Must answer in well under 20 ms (CONTRACT §13).
        async fn status(
            &self,
            request: tonic::Request<super::StatusRequest>,
        ) -> std::result::Result<tonic::Response<super::StatusResponse>, tonic::Status>;
        /// Local kill switch for the Worker role: instant, works offline, not persisted across restarts.
        async fn pause(
            &self,
            request: tonic::Request<super::PauseRequest>,
        ) -> std::result::Result<tonic::Response<super::PauseResponse>, tonic::Status>;
        async fn resume(
            &self,
            request: tonic::Request<super::PauseRequest>,
        ) -> std::result::Result<tonic::Response<super::PauseResponse>, tonic::Status>;
        /// Base URLs + repo-scoped local token for tools (`moochy env`). `rotate` invalidates every token.
        async fn env(
            &self,
            request: tonic::Request<super::EnvRequest>,
        ) -> std::result::Result<tonic::Response<super::EnvResponse>, tonic::Status>;
        /// Repo owner: sign a pending donor approval / membership change / repo claim with this device
        /// (plan 06 §5). The Node only signs a request the Relay pushed (ApprovalRequests), after
        /// checking its exact body; `dry_run` returns what would be signed without signing.
        async fn approve(
            &self,
            request: tonic::Request<super::ApproveRequest>,
        ) -> std::result::Result<tonic::Response<super::SignResponse>, tonic::Status>;
        async fn members(
            &self,
            request: tonic::Request<super::MembersRequest>,
        ) -> std::result::Result<tonic::Response<super::SignResponse>, tonic::Status>;
        async fn claim(
            &self,
            request: tonic::Request<super::ClaimRequest>,
        ) -> std::result::Result<tonic::Response<super::SignResponse>, tonic::Status>;
        /// CONTRACT §19.3: ORG_REPO_ADDED / ORG_REPO_REMOVED previews (dry run only, like Claim).
        async fn org_repo(
            &self,
            request: tonic::Request<super::OrgRepoRequest>,
        ) -> std::result::Result<tonic::Response<super::SignResponse>, tonic::Status>;
        /// Requests waiting for this owner's signature.
        async fn pending(
            &self,
            request: tonic::Request<super::PendingRequest>,
        ) -> std::result::Result<tonic::Response<super::PendingResponse>, tonic::Status>;
        /// Owner key (CONTRACT §15.4, KEYLOG §4): the foreground CLI signed this key-log entry with the
        /// owner key after the user confirmed it; the Node never holds the owner key, it only relays the
        /// signed entry over its session and returns the relay's verdict. Approve/Members/Claim are then
        /// called with dry_run = true (preview only).
        async fn submit_entry(
            &self,
            request: tonic::Request<super::SubmitEntryRequest>,
        ) -> std::result::Result<tonic::Response<super::SignResponse>, tonic::Status>;
        /// Donations (`moochy donate`, `moochy donations`): relayed as-is to NodeLink ListDonations /
        /// Donate / DonationAction on the node's authenticated session (the relay knows the user from
        /// the session, never from a field). `request`/`response` are the link.proto messages' bytes.
        async fn donations(
            &self,
            request: tonic::Request<super::DonationsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DonationsResponse>,
            tonic::Status,
        >;
        /// `moochy verify <receipt_ref>` (E63): fetch the public projection over the link and check the
        /// donor's signature against the device key in this node's verified key-log mirror.
        async fn verify(
            &self,
            request: tonic::Request<super::VerifyRequest>,
        ) -> std::result::Result<tonic::Response<super::VerifyResponse>, tonic::Status>;
        /// `moochy owner trust <ok_id>` (CONTRACT §16.6): mark an owner key of this account that was
        /// created elsewhere (a passkey registered on the web) as known, so the monitor stops alerting.
        async fn trust_owner_key(
            &self,
            request: tonic::Request<super::TrustOwnerKeyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TrustOwnerKeyResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the Journal method.
        type JournalStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::JournalEntry, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Local audit journal (metadata only). `follow` keeps the stream open for new entries.
        async fn journal(
            &self,
            request: tonic::Request<super::JournalRequest>,
        ) -> std::result::Result<tonic::Response<Self::JournalStream>, tonic::Status>;
        /// Server streaming response type for the McpPipe method.
        type McpPipeStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::McpDown, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// stdio MCP shim: first message McpOpen, then raw newline-delimited JSON-RPC bytes both ways.
        async fn mcp_pipe(
            &self,
            request: tonic::Request<tonic::Streaming<super::McpUp>>,
        ) -> std::result::Result<tonic::Response<Self::McpPipeStream>, tonic::Status>;
        /// Graceful stop (`moochy down`).
        async fn shutdown(
            &self,
            request: tonic::Request<super::ShutdownRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ShutdownResponse>,
            tonic::Status,
        >;
        /// `moochy logout`: ask the relay to revoke this device (KEY_REVOKED), then stop.
        async fn logout(
            &self,
            request: tonic::Request<super::LogoutRequest>,
        ) -> std::result::Result<tonic::Response<super::LogoutResponse>, tonic::Status>;
        /// `moochy report <task>`: evidence bundle for a task this Gateway consumed (06 §9): receipt,
        /// checkpoints, response bytes and only S_resp (never the request).
        async fn report(
            &self,
            request: tonic::Request<super::ReportRequest>,
        ) -> std::result::Result<tonic::Response<super::ReportResponse>, tonic::Status>;
        /// Owner and member calls relayed as-is on the node's session (like Donations): `op` names the
        /// NodeLink RPC; `request`/`response` are its link.proto messages' bytes. Ops: set_device_cap,
        /// create_box_token, list_boxes, revoke_box.
        async fn link_call(
            &self,
            request: tonic::Request<super::LinkCallRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LinkCallResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct LocalControlServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> LocalControlServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for LocalControlServer<T>
    where
        T: LocalControl,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/moochy.v1.LocalControl/Status" => {
                    #[allow(non_camel_case_types)]
                    struct StatusSvc<T: LocalControl>(pub Arc<T>);
                    impl<
                        T: LocalControl,
                    > tonic::server::UnaryService<super::StatusRequest>
                    for StatusSvc<T> {
                        type Response = super::StatusResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StatusRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LocalControl>::status(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StatusSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/moochy.v1.LocalControl/Pause" => {
                    #[allow(non_camel_case_types)]
                    struct PauseSvc<T: LocalControl>(pub Arc<T>);
                    impl<
                        T: LocalControl,
                    > tonic::server::UnaryService<super::PauseRequest> for PauseSvc<T> {
                        type Response = super::PauseResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PauseRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LocalControl>::pause(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PauseSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/moochy.v1.LocalControl/Resume" => {
                    #[allow(non_camel_case_types)]
                    struct ResumeSvc<T: LocalControl>(pub Arc<T>);
                    impl<
                        T: LocalControl,
                    > tonic::server::UnaryService<super::PauseRequest> for ResumeSvc<T> {
                        type Response = super::PauseResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PauseRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LocalControl>::resume(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ResumeSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/moochy.v1.LocalControl/Env" => {
                    #[allow(non_camel_case_types)]
                    struct EnvSvc<T: LocalControl>(pub Arc<T>);
                    impl<T: LocalControl> tonic::server::UnaryService<super::EnvRequest>
                    for EnvSvc<T> {
                        type Response = super::EnvResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::EnvRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LocalControl>::env(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = EnvSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/moochy.v1.LocalControl/Approve" => {
                    #[allow(non_camel_case_types)]
                    struct ApproveSvc<T: LocalControl>(pub Arc<T>);
                    impl<
                        T: LocalControl,
                    > tonic::server::UnaryService<super::ApproveRequest>
                    for ApproveSvc<T> {
                        type Response = super::SignResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ApproveRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LocalControl>::approve(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ApproveSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/moochy.v1.LocalControl/Members" => {
                    #[allow(non_camel_case_types)]
                    struct MembersSvc<T: LocalControl>(pub Arc<T>);
                    impl<
                        T: LocalControl,
                    > tonic::server::UnaryService<super::MembersRequest>
                    for MembersSvc<T> {
                        type Response = super::SignResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MembersRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LocalControl>::members(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = MembersSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/moochy.v1.LocalControl/Claim" => {
                    #[allow(non_camel_case_types)]
                    struct ClaimSvc<T: LocalControl>(pub Arc<T>);
                    impl<
                        T: LocalControl,
                    > tonic::server::UnaryService<super::ClaimRequest> for ClaimSvc<T> {
                        type Response = super::SignResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ClaimRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LocalControl>::claim(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ClaimSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/moochy.v1.LocalControl/OrgRepo" => {
                    #[allow(non_camel_case_types)]
                    struct OrgRepoSvc<T: LocalControl>(pub Arc<T>);
                    impl<
                        T: LocalControl,
                    > tonic::server::UnaryService<super::OrgRepoRequest>
                    for OrgRepoSvc<T> {
                        type Response = super::SignResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::OrgRepoRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LocalControl>::org_repo(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = OrgRepoSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/moochy.v1.LocalControl/Pending" => {
                    #[allow(non_camel_case_types)]
                    struct PendingSvc<T: LocalControl>(pub Arc<T>);
                    impl<
                        T: LocalControl,
                    > tonic::server::UnaryService<super::PendingRequest>
                    for PendingSvc<T> {
                        type Response = super::PendingResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PendingRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LocalControl>::pending(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PendingSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/moochy.v1.LocalControl/SubmitEntry" => {
                    #[allow(non_camel_case_types)]
                    struct SubmitEntrySvc<T: LocalControl>(pub Arc<T>);
                    impl<
                        T: LocalControl,
                    > tonic::server::UnaryService<super::SubmitEntryRequest>
                    for SubmitEntrySvc<T> {
                        type Response = super::SignResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SubmitEntryRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LocalControl>::submit_entry(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SubmitEntrySvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/moochy.v1.LocalControl/Donations" => {
                    #[allow(non_camel_case_types)]
                    struct DonationsSvc<T: LocalControl>(pub Arc<T>);
                    impl<
                        T: LocalControl,
                    > tonic::server::UnaryService<super::DonationsRequest>
                    for DonationsSvc<T> {
                        type Response = super::DonationsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DonationsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LocalControl>::donations(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DonationsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/moochy.v1.LocalControl/Verify" => {
                    #[allow(non_camel_case_types)]
                    struct VerifySvc<T: LocalControl>(pub Arc<T>);
                    impl<
                        T: LocalControl,
                    > tonic::server::UnaryService<super::VerifyRequest>
                    for VerifySvc<T> {
                        type Response = super::VerifyResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::VerifyRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LocalControl>::verify(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = VerifySvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/moochy.v1.LocalControl/TrustOwnerKey" => {
                    #[allow(non_camel_case_types)]
                    struct TrustOwnerKeySvc<T: LocalControl>(pub Arc<T>);
                    impl<
                        T: LocalControl,
                    > tonic::server::UnaryService<super::TrustOwnerKeyRequest>
                    for TrustOwnerKeySvc<T> {
                        type Response = super::TrustOwnerKeyResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::TrustOwnerKeyRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LocalControl>::trust_owner_key(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = TrustOwnerKeySvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/moochy.v1.LocalControl/Journal" => {
                    #[allow(non_camel_case_types)]
                    struct JournalSvc<T: LocalControl>(pub Arc<T>);
                    impl<
                        T: LocalControl,
                    > tonic::server::ServerStreamingService<super::JournalRequest>
                    for JournalSvc<T> {
                        type Response = super::JournalEntry;
                        type ResponseStream = T::JournalStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::JournalRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LocalControl>::journal(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = JournalSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/moochy.v1.LocalControl/McpPipe" => {
                    #[allow(non_camel_case_types)]
                    struct McpPipeSvc<T: LocalControl>(pub Arc<T>);
                    impl<T: LocalControl> tonic::server::StreamingService<super::McpUp>
                    for McpPipeSvc<T> {
                        type Response = super::McpDown;
                        type ResponseStream = T::McpPipeStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<tonic::Streaming<super::McpUp>>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LocalControl>::mcp_pipe(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = McpPipeSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/moochy.v1.LocalControl/Shutdown" => {
                    #[allow(non_camel_case_types)]
                    struct ShutdownSvc<T: LocalControl>(pub Arc<T>);
                    impl<
                        T: LocalControl,
                    > tonic::server::UnaryService<super::ShutdownRequest>
                    for ShutdownSvc<T> {
                        type Response = super::ShutdownResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ShutdownRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LocalControl>::shutdown(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ShutdownSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/moochy.v1.LocalControl/Logout" => {
                    #[allow(non_camel_case_types)]
                    struct LogoutSvc<T: LocalControl>(pub Arc<T>);
                    impl<
                        T: LocalControl,
                    > tonic::server::UnaryService<super::LogoutRequest>
                    for LogoutSvc<T> {
                        type Response = super::LogoutResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LogoutRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LocalControl>::logout(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LogoutSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/moochy.v1.LocalControl/Report" => {
                    #[allow(non_camel_case_types)]
                    struct ReportSvc<T: LocalControl>(pub Arc<T>);
                    impl<
                        T: LocalControl,
                    > tonic::server::UnaryService<super::ReportRequest>
                    for ReportSvc<T> {
                        type Response = super::ReportResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ReportRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LocalControl>::report(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ReportSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/moochy.v1.LocalControl/LinkCall" => {
                    #[allow(non_camel_case_types)]
                    struct LinkCallSvc<T: LocalControl>(pub Arc<T>);
                    impl<
                        T: LocalControl,
                    > tonic::server::UnaryService<super::LinkCallRequest>
                    for LinkCallSvc<T> {
                        type Response = super::LinkCallResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LinkCallRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LocalControl>::link_call(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LinkCallSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for LocalControlServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "moochy.v1.LocalControl";
    impl<T> tonic::server::NamedService for LocalControlServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
